### ISSUE TITLE
查詢後回退頁面會有如下情況

### ISSUE THREAD

**Issue by BoxMars** [UMHelper/UM-Eelective-Helper-Web#2]
![image](https://user-images.githubusercontent.com/16847158/91645039-603df300-ea74-11ea-87f9-ab8646ff4a86.png)

**Comment by Admittedly-Goat** [comment]
这个应该是MDL库的问题...
我会在接下来的开发过程中逐步改用自己写的CSS，这样就不会出现这种尴尬的问题了
