### ISSUE TITLE
New UI system (Fluent Design considered)

### ISSUE THREAD

**Issue by stiven-ding** [UMHelper/UM-Eelective-Helper-Web#3]
[Fluent Design (link)](https://fluentdesignforweb.github.io/documentation/#/date_time_input) considered.

![image](https://user-images.githubusercontent.com/12206788/91662571-eeb68100-eb15-11ea-97bf-9d8d44ad7328.png)

**Comment by Admittedly-Goat** [comment]
我应该不会用各种CSS库，用其它人的预设感觉总有些拘束
界面风格一定会遵循Windows“大色块”的设计
预计会在next-gen里体现

**Comment by stiven-ding** [comment]
> 我应该不会用各种CSS库，用其它人的预设感觉总有些拘束
> 界面风格一定会遵循Windows“大色块”的设计
> 预计会在next-gen里体现

For reference.
